Web/WebEminari.Web/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

using WebEminari.Data;
using WebEminari.Data.Models;
using WebEminari.Services.Data;
using WebEminari.Services.Messaging;
using WebEminari.Web.ViewModels.Comments;
using WebEminari.Web.ViewModels.WebEminars;

namespace WebEminari.Web.Controllers
{
    public class CommentsController : BaseController
    {

        private readonly ICommentsService commentsService;

        public CommentsController(ICommentsService commentsService)
            => this.commentsService = commentsService;

        [HttpGet]
        public IActionResult Create() => this.RedirectToAction("All", "WebEminars");

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CommentInputModel commentViewModel)
        {
            var parentId =
               commentViewModel.ParentId == 0 ?
                   (int?)null :
                   commentViewModel.ParentId;

            commentViewModel.ApplicationUserId = this.GetUserId();
            var id = new { id = commentViewModel.WebEminarId };

            if (!this.ModelState.IsValid)
            {
                // var changedModel = new LessonViewModel { LessonId = commentViewModel.LessonId };
                return this.RedirectToAction("Details", "WebEminars", id);
            }

            await this.commentsService.CreateCommentAsync(commentViewModel, parentId);
            return this.RedirectToAction("Details", "WebEminars", id);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            CommentEditModel comment = await this.commentsService.GetCommentByIdWithDeletedAsync<CommentEditModel>(id);
            return this.View(comment);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(CommentEditModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            if (model.ApplicationUserId != this.GetUserId())
            {
                return this.View(nameof(this.Unauthorized));
            }

            await this.commentsService.EditCommentAsync(model);
            return this.RedirectToAction(nameof(this.MyComments));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var commentModel = await this.commentsService.GetCommentByIdWithDeletedAsync<CommentDeleteModel>(id);
            return this.View(commentModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(CommentDeleteModel model)
        {
            if (model.ApplicationUserId != this.GetUserId())
            {
                return this.View("Unauthorized");
            }

            await this.commentsService.SoftDeleteCommentByIdAsync(model.Id);
            return this.RedirectToAction(nameof(this.MyComments));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> MyComments()
        {
            IEnumerable<CommentByMeModel> commentByMe = await this.commentsService.GetCommentsMadeByMeAsync(this.GetUserId());
            return this.View(commentByMe);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> WebEminarsComments()
        {
            IEnumerable<CommentViewModel> comments = await this.commentsService.GetCommentsMadeInMyWebEminarAsync(this.GetUserId());
            return this.View(comments);
        }
    }
}

Web/WebEminari.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using WebEminari.Data;
using WebEminari.Services.Data;
using WebEminari.Web.ViewModels.Administration.Report;
using WebEminari.Web.ViewModels.Reports.Comments;
using WebEminari.Web.ViewModels.Reports.WebEminars;

namespace WebEminari.Web.Controllers
{
    public class ReportController : BaseController
    {
        private readonly IWebEminarsService lessonsService;
        private readonly ICommentsService commentsService;
        private readonly IReportsService reportsService;
        private readonly ApplicationDbContext context;

        public ReportController(
            IWebEminarsService lessonsService,
            ICommentsService commentsService,
            IReportsService reportsService,
            ApplicationDbContext context)
        {
            this.lessonsService = lessonsService;
            this.commentsService = commentsService;
            this.reportsService = reportsService;
            this.context = context;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> CommentsReports()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            IEnumerable<AdminReportViewModel> reports = await this.reportsService.GetAllReportsForCommentsAsync<AdminReportViewModel>(userId);

            return this.View(reports);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> WebEminarsReports()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            IEnumerable<AdminReportViewModel> reports = await this.reportsService.GetAllReportsForWebEminarsAsync<AdminReportViewModel>(userId);

            return this.View(reports);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> WebEminarReportsCreatedByMe()
        {
            IEnumerable<WebEminarReportViewModel> models = await this.reportsService.GetWebEminarReportsCreatedByMeAsync(this.GetUserId());
            return this.View(models);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> WebEminar(int id)
        {
            if (!this.lessonsService.Contains(id))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            WebEminarReportInputModel lessonToReport = this.lessonsService.GetById<WebEminarReportInputModel>(id);
            return this.View(lessonToReport);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> WebEminar(WebEminarReportInputModel model)
        {
            model.ApplicationUserId = this.GetUserId();

            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            await this.reportsService.CreateWebEminarReportAsync(model);
            return this.RedirectToAction(nameof(this.WebEminarReportsCreatedByMe));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> WebEminarEdit(int reportId)
        {
            if (!this.reportsService.Contains(reportId))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            WebEminarReportEditModel model = await this.reportsService.GetReportByIdAsync<WebEminarReportEditModel>(reportId);
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> WebEminarEdit(WebEminarReportEditModel model)
        {
            if (!this.reportsService.Contains(model.ReportId))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.reportsService.EditWebEminarReportAsync(model);
            return this.RedirectToAction(nameof(this.WebEminarReportsCreatedByMe));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> WebEminarDelete(int reportId)
        {
            if (!this.reportsService.Contains(reportId))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            WebEminarReportDeleteModel model = await this.reportsService.GetReportByIdAsync<WebEminarReportDeleteModel>(reportId);
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> WebEminarDelete(WebEminarReportDeleteModel model)
        {
            if (!this.reportsService.Contains(model.ReportId))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }
            
         
             await this.reportsService.SoftDeleteReportByIdAsync(model.ReportId);
             return this.RedirectToAction(nameof(this.WebEminarReportsCreatedByMe));
        }

        [Authorize]
        public async Task<IActionResult> CommentReportsCreatedByMe()
        {
            IEnumerable<CommentReportViewModel> models = await this.reportsService.GetCommentReportsCreatedByMeAsync(this.GetUserId());
            return this.View(models);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Comment(int id)
        {
            if (!this.commentsService.Contains(id))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            CommentReportInputModel model = await this.commentsService.GetCommentByIdWithDeletedAsync<CommentReportInputModel>(id);
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Comment(CommentReportInputModel model)
        {
            model.ApplicationUserId = this.GetUserId();

            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            await this.reportsService.CreateCommentReportAsync(model);
            return this.RedirectToAction(nameof(this.CommentReportsCreatedByMe));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> CommentEdit(int reportId)
        {
            if (!this.reportsService.Contains(reportId))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            CommentReportEditModel model = await this.reportsService.GetReportByIdAsync<CommentReportEditModel>(reportId);
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CommentEdit(CommentReportEditModel model)
        {
            if (!this.reportsService.Contains(model.ReportId))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

   
            await this.reportsService.EditCommentReportAsync(model);
            return this.RedirectToAction(nameof(this.CommentReportsCreatedByMe));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> CommentDelete(int reportId)
        {
            if (!this.reportsService.Contains(reportId))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            CommentReportDeleteModel model = await this.reportsService.GetReportByIdAsync<CommentReportDeleteModel>(reportId);
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CommentDelete(CommentReportDeleteModel model)
        {
            if (!this.reportsService.Contains(model.ReportId))
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            var items = this.context.WebEminars;
            if (!items.Any(webEminar => webEminar.AddedByUserId == this.GetUserId()))
            {
                return this.View(nameof(this.Unauthorized));
            }
          


            await this.reportsService.SoftDeleteReportByIdAsync(model.ReportId);
            return this.RedirectToAction(nameof(this.CommentReportsCreatedByMe));
        }
    }
}

Web/WebEminari.Web/Views/Shared/Components/AllComments/Default.cshtml
@model IEnumerable<WebEminari.Web.ViewModels.Comments.CommentViewModel>

<style>
    .comment-img {
        width: 3rem;
        height: 3rem;
    }

    .comment-replies .comment-img {
        width: 1.75rem;
        height: 1.75rem;
    }
</style>
<div class="bg-white rounded-3 shadow-sm p-4">

    <h4 class="mb-4">@Model.Count() Comments</h4>
    @foreach (var item in Model.Where(x => x.ParentId == null))
    {
<div class="py-3">
    <div class="d-flex comment">
        <img class="rounded-circle comment-img"
             src="~/ProfileImages/@item.ApplicationUserImagePath" />
        <div class="flex-grow-1 ms-3">
            <div class="mb-1"><a href="#" class="fw-bold link-dark me-1">@item.ApplicationUserUserName</a> <span class="text-muted text-nowrap"><small class="text-muted"><time datetime="@item.CreatedOn.ToString("O")">@item.CreatedOn.ToString("g")</time></small></span></div>
            <div class="mb-2">@item.Content</div>
            <div class="hstack align-items-center mb-2">
                @if (User.Identity?.Name == item.ApplicationUserUserName)
                {
        <a class="btn btn-sm btn-danger text-uppercase" asp-controller="Comments" asp-action="Delete" asp-route-id="@item.Id">DELETE</a>
        <a class="btn btn-sm btn-warning text-uppercase ms-3" asp-controller="Comments" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                }
                 else
                 {
                  <a class="btn btn-sm btn-warning text-uppercase" asp-controller="Report" asp-action="Comment" asp-route-id="@item.Id">Report</a>
                 }
            </div>
            <div onclick="Reply(event, @item.Id, @item.WebEminarId)">
                <form id="replyForm" asp-controller="Comments" asp-action="Create">
                    <input id="webEminarId" name="WebEminarId" value="0" type="hidden" />
                    <input id="parentId" type="hidden" name="ParentId" value="0" />
                    <textarea placeholder="Write your reply here" class="form-control" id="content" name="Content"></textarea>
                    <button class="btn btn-info" style="float: right; margin-top: 10px">Reply</button>
                </form>
            </div>


        </div>
    </div>
</div>
                @foreach (var reply in Model.Where(x => x.ParentId == item.Id))
                {
<div class="comment-replies mt-4 bg-light p-3 rounded">
    <div class="d-flex py-2">
        <img class="rounded-circle comment-img"
             src="~/ProfileImages/@reply.ApplicationUserImagePath" />
        <div class="flex-grow-1 ms-3">
            <div class="mb-1"><a href="#" class="fw-bold link-dark pe-1">@reply.ApplicationUserUserName</a> <span class="text-muted text-nowrap"> <small class="text-muted"><time datetime="@reply.CreatedOn.ToString("O")">@reply.CreatedOn.ToString("g")</time></small></span></div>
            <div class="mb-2">@reply.Content</div>
            <div class="hstack align-items-center">
                @if (User.Identity?.Name == reply.ApplicationUserUserName)
                {
            <a class="btn btn-sm btn-danger text-uppercase" asp-controller="Comments" asp-action="Delete" asp-route-id="@reply.Id">DELETE</a>
             <a class="btn btn-sm btn-warning text-uppercase ms-3" asp-controller="Comments" asp-action="Edit" asp-route-id="@reply.Id">Edit</a> 
             }
                 else
                 {
                 <a class="btn btn-sm btn-warning text-uppercase" asp-controller="Report" asp-action="Comment" asp-route-id="@item.Id">Report</a>
                 }
            </div>
        </div>
    </div>
</div>        }
                               
                                         
<hr />
}
    </div>



    <script>
        function Reply(event, parentid, webeminarid) {
            let parentId = event.currentTarget.querySelector('#parentId');
            let webeminarId = event.currentTarget.querySelector('#webEminarId');
            parentId.value = parentid;
            webeminarId.value = webeminarid;
        }

    </script>