Web/WebEminari.Web/Areas/Administration/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using WebEminari.Services.Data;
using WebEminari.Web.ViewModels.Organizations;

namespace WebEminari.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize(Roles = "Administrator")]
    public class OrganizationsController : Controller
    {
        private readonly IOrganizationsService organizationsService;

        public OrganizationsController(IOrganizationsService organizationsService)
        {
            this.organizationsService = organizationsService;
        }

        public IActionResult Index()
        {
            var models = this.organizationsService
                .GetAllAsync<OrganizationViewModel>(true);

            return this.View(models);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = this.organizationsService.GetById<OrganizationEditModel>(id, true);

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(OrganizationEditModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.organizationsService.EditAsync(model, true);

            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Delete(int id)
        {
            await this.organizationsService.HardDeleteAsync(id);

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/WebEminari.Web/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using WebEminari.Services.Data;
using WebEminari.Web.ViewModels.Organizations;

namespace WebEminari.Web.Controllers
{
    public class OrganizationController : BaseController
    {
        private readonly IOrganizationsService organizationsService;

        public OrganizationController(IOrganizationsService organizationsService)
            => this.organizationsService = organizationsService;

        [Authorize]
        public IActionResult Joined()
        {
            var models = this.organizationsService
                .GetByMemberId<OrganizationViewModel>(this.GetUserId());

            return this.View(models);
        }

        [Authorize]
        public IActionResult ByMe()
        {
            var models = this.organizationsService
                .GetByCreatorId<OrganizationViewModel>(this.GetUserId());

            return this.View(models);
        }

        [Authorize]
        public async Task<IActionResult> Join(int id)
        {
            await this.organizationsService.AddUserAsync(id, this.GetUserId());

            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize]
        public async Task<IActionResult> Leave(int id)
        {
            await this.organizationsService.RemoveUserAsync(id, this.GetUserId());

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult View(int id)
        {
            var model = this.organizationsService.GetById<OrganizationViewModel>(id);
            if (model == null)
            {
                this.Response.StatusCode = 404;
                return this.NotFound();
            }

            return this.View(model);
        }

        public IActionResult All()
        {
            var models = this.organizationsService
                .GetAllAsync<OrganizationViewModel>();

            return this.View(models);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = this.organizationsService.GetById<OrganizationEditModel>(id);

            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(OrganizationEditModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            if (model.CreatorId.Equals(this.GetUserId()))
            {
                await this.organizationsService.EditAsync(model);
            }

            return this.RedirectToAction(nameof(this.View), new { id = model.Id });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = this.GetUserId();
            await this.organizationsService.SoftDeleteAsync(id, userId);

            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(OrganizationInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var organizationId = await this.organizationsService.CreateAsync(model, this.GetUserId());

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            await this.organizationsService.AddUserAsync(organizationId, userId);

            return this.RedirectToAction(nameof(this.All));
        }
    }
}

Web/WebEminari.Web/Areas/Administration/Views/Organizations/Edit.cshtml
@model OrganizationEditModel
@{ ViewData["Title"] = "Edit an organization"; }

<div class="container-fluid">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit</h6>
        </div>

        <div class="card-body">

            <h4>Организация</h4>
            <hr />
            <div class="container">
                <div class="row">
                    <div class="offset-md-3 col-md-6 text-center">
                        <form asp-area="Administration" asp-controller="Organizations" asp-action="Edit" method="post">
                            <input type="hidden" asp-for="CreatorId" />

                            <div class="form-group">
                                <label asp-for="Name"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Description"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>

                            <div class="form-group form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" asp-for="IsDeleted" />
                                    @Html.DisplayNameFor(model => model.IsDeleted)
                                </label>
                            </div>

                            <input class="btn btn-sm btn-outline-success float-right" type="submit" name="submit" value="Submit" />
                            <a asp-action="Index" class="btn btn-sm btn-outline-dark float-left"><i class="fas fa-arrow-left"></i> Back to all</a>
                        </form>
                    </div>
                </div>
                </div>
</div>
</div>
</div>

Web/WebEminari.Web/Areas/Administration/Views/Organizations/Index.cshtml
@model IEnumerable<OrganizationViewModel>
@{ ViewData["Title"] = "Organizations administration"; }

<!-- Begin Page Content -->
<div class="container-fluid">


    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Организации</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th>
                                Description
                            </th>
                            <th>
                                Member count
                            </th>
                            <th>
                                Date created
                            </th>
                            <th>
                                Is deleted
                            </th>
                            <th>
                                Actions
                            </th>
                            <th>
                                Management
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var organization in @Model)
                        {
            <tr>
                <td>
                    @organization.Name
                </td>
                <td>
                    @organization.Description
                </td>
                <td>
                    @organization.UsersCount
                </td>
                <td>
                    <time datetime="@organization.CreatedOn.ToString("O")">
                        @organization.CreatedOn.ToString("g")
                    </time>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => organization.IsDeleted)
                </td>
                <td>

                    <a asp-area="" asp-controller="Organization" asp-action="Leave" asp-route-id="@organization.Id"
                       class="btn btn-sm btn-outline-danger">
                        Leave
                    </a>

                    <a asp-area="" asp-controller="Organization" asp-action="Join" asp-route-id="@organization.Id"
                       class="btn btn-sm btn-outline-success">
                        Join
                    </a>
                    <a asp-area="" asp-controller="Organization" asp-action="View" asp-route-id="@organization.Id"
                       class="btn btn-sm btn-outline-primary mt-1 mb-1">
                        View
                    </a>
                </td>
                <td>

                    <a asp-controller="Organizations" asp-action="Edit" asp-route-id="@organization.Id"
                       class="btn btn-sm btn-outline-success mb-1">
                        Edit / Soft delete
                    </a>

                    <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#confirmModal">
                        Hard delete (Irreversible)
                    </button>

                    <!-- Delete Modal -->
                    <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content ">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="confirmModalLabel">Delete confirmation</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                <div class="modal-body container">
                                    <div>Are you sure that you want to delete this organization?</div>
                                </div>

                                <form asp-area="Administration" asp-controller="Organizations" asp-action="Delete" asp-route-id="@organization.Id" method="post">
                                    <div class="modal-footer">
                                        <input type="submit" value="Delete" class="btn btn-sm btn-outline-danger" />
                                        <button type="button" class="btn btn-sm btn-outline-dark" data-dismiss="modal">Cancel</button>
                                    </div>
                                </form>


                            </div>
                        </div>
                    </div>

                </td>
            </tr>
}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>