Web/WebEminari.Web/Areas/Administration/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using WebEminari.Services.Data;
using WebEminari.Web.ViewModels;
using WebEminari.Web.ViewModels.Administration;
using WebEminari.Web.ViewModels.HelperModels;

namespace WebEminari.Web.Areas.Administration.Controllers
{
    public class CommentsController : AdministrationController
    {
        private readonly ICommentsService commentsService;

        public CommentsController(ICommentsService commentsService)
            => this.commentsService = commentsService;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var allComments = await this.commentsService.GetAllCommentsAsync();
         

            return this.View(allComments);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            AdminCommentEditModel comment = await this.commentsService.GetCommentByIdWithDeletedAsync<AdminCommentEditModel>(id);
            return this.View(comment);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AdminCommentEditModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.commentsService.EditCommentByAdminAsync(model);
            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            AdminCommentDeleteModel comment = await this.commentsService.GetCommentByIdWithDeletedAsync<AdminCommentDeleteModel>(id);
            return this.View(comment);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.commentsService.HardDeleteCommentByIdAsync(id);
            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/WebEminari.Web/Areas/Administration/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using WebEminari.Services.Data;
using WebEminari.Web.ViewModels.Administration.Report;
using WebEminari.Web.ViewModels.HelperModels;

namespace WebEminari.Web.Areas.Administration.Controllers
{
    public class ReportsController : AdministrationController
    {
        private readonly IReportsService reportsService;

        public ReportsController(IReportsService reportsService)
            => this.reportsService = reportsService;

        [HttpGet]
        public async Task<IActionResult> IndexComments()
        {
            IEnumerable<AdminReportViewModel> reports = await this.reportsService.GetAllCommentsReportsAsync<AdminReportViewModel>();

            return this.View(reports);
        }
        [HttpGet]
        public async Task<IActionResult> IndexWebEminars()
        {
            IEnumerable<AdminReportViewModel> reports = await this.reportsService.GetAllWebinarsReportsAsync<AdminReportViewModel>();

            return this.View(reports);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            IEnumerable<AdminReportEditModel> reports = await this.reportsService.GetAllReportsAsync<AdminReportEditModel>();
            AdminReportEditModel report = reports.FirstOrDefault(x => x.Id == id);
            return this.View(report);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AdminReportEditModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.reportsService.EditReportAdministrationAsync(model);
            if (model.CommentId != null)
            {
                return this.RedirectToAction(nameof(this.IndexComments));
            }
            else 
            {
                return this.RedirectToAction(nameof(this.IndexWebEminars));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            IEnumerable<AdminReportDeleteModel> reports = await this.reportsService.GetAllReportsAsync<AdminReportDeleteModel>();
            AdminReportDeleteModel report = reports.FirstOrDefault(x => x.Id == id);
            return this.View(report);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            IEnumerable<AdminReportDeleteModel> reports = await this.reportsService.GetAllReportsAsync<AdminReportDeleteModel>();
            await this.reportsService.HardDeleteReportByIdAsync(id);
            AdminReportDeleteModel report = reports.FirstOrDefault(x => x.Id == id);
            if (report.CommentId != null)
            {
                return this.RedirectToAction(nameof(this.IndexComments));
            }
            else
            {
                return this.RedirectToAction(nameof(this.IndexWebEminars));
            }
        }
    }
}

Web/WebEminari.Web/Areas/Administration/Controllers/WebEminarsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebEminari.Data;
using WebEminari.Data.Common.Repositories;
using WebEminari.Data.Models;
using WebEminari.Services.Data;
using WebEminari.Web.ViewModels.WebEminars;

namespace WebEminari.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize(Roles = "Administrator")]
    public class WebEminarsController : Controller
    {
        private readonly IDeletableEntityRepository<WebEminar> dataRepository;

        private readonly IDeletableEntityRepository<UserBooking> userBookingsRepository;

        private readonly IDeletableEntityRepository<Vote> votesRepository;

        private readonly IDeletableEntityRepository<Comment> commentsRepository;

        private readonly IDeletableEntityRepository<Report> reportsRepository;

        private readonly IDeletableEntityRepository<Like> likesRepository;

        private readonly ICategoriesService categoriesService;

        public IWebHostEnvironment WebHostEnviroment { get; }

        private readonly UserManager<ApplicationUser> userManager;

        private readonly IWebEminarsService webEminarService;

        private readonly ApplicationDbContext context;

        private readonly IInformationService informationService;

        public WebEminarsController(IInformationService informationService, IDeletableEntityRepository<Like> likesRepository, IDeletableEntityRepository<Report> reportsRepository, IDeletableEntityRepository<Comment> commentsRepository, IDeletableEntityRepository<Vote> votesRepository, IDeletableEntityRepository<UserBooking> userBookingsRepository, IDeletableEntityRepository<WebEminar> dataRepository, ICategoriesService categoriesService, IWebEminarsService webEminarService, ApplicationDbContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnviroment)
        {
            this.likesRepository = likesRepository;
            this.reportsRepository = reportsRepository;
            this.commentsRepository = commentsRepository;
            this.votesRepository = votesRepository;
            this.userBookingsRepository = userBookingsRepository;
            this.userManager = userManager;
            this.context = context;
            this.WebHostEnviroment = webHostEnviroment;
            this.webEminarService = webEminarService;
            this.categoriesService = categoriesService;
            this.dataRepository = dataRepository;
            this.informationService = informationService;
        }


        // GET: Administration/WebEminars
        public async Task<IActionResult> Index()
        {
           
            var model = await this.informationService.GenerateAdministrationIndexViewModel();

            return this.View(model);
        }
        public async Task<IActionResult> IndexWebEminars()
        {
            return this.View(await this.dataRepository
               .AllWithDeleted()
               .Where(webEminars => webEminars.ImageName != null)
               .ToListAsync());
        }
        public async Task<IActionResult> IndexWebEminarsWithVideos()
        {
            return this.View(await this.dataRepository
               .AllWithDeleted()
               .Where(webEminars => webEminars.ImageName == null)
               .ToListAsync());
        }
        public IActionResult BookedPeople(int id)
        {
            var webEminar = this.webEminarService.GetById<WebEminarViewModel>(id);
            var userBookings = context.UserBookings.Where(x => x.WebEminarId == webEminar.Id);
            return this.View(userBookings);
        }

        // GET: Administration/WebEminars/Create
        public IActionResult Create()
        {
            var viewModel = new WebEminarViewModel();

            viewModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(WebEminarViewModel input)
        {
            if (!this.ModelState.IsValid || input.Image == null)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

                return this.View(input);
            }

            string stringFile = this.UploadFile(input);
            var user = await this.userManager.GetUserAsync(this.User);


            await this.webEminarService.CreateAsync(input, user.Id, stringFile);

            return this.Redirect("IndexWebEminars");
        }
        public IActionResult CreateWithVideo()
        {
            var viewModel = new WebEminarWithVideoViewModel();

            viewModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateWithVideo(WebEminarWithVideoViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            await this.webEminarService.CreateWithVideoAsync(input, user.Id);

            return this.Redirect("IndexWebEminarsWithVideos");
        }

        public IActionResult Edit(int id)
        {
       
                var inputModel = this.webEminarService.GetByIdAdmin<WebEminarViewModel>(id);

                inputModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

                return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, WebEminarViewModel input)
        {
     
            string stringFile = input.ImageName;
            if (input.Image != null)
            {
                stringFile = this.UploadFile(input);
            }

            await this.webEminarService.UpdateAdminAsync(id, input, stringFile);

            return this.RedirectToAction("IndexWebEminars");
        }
        public IActionResult EditWithVideo(int id)
        {

                var inputModel = this.webEminarService.GetById<WebEminarWithVideoViewModel>(id);

                inputModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

                return this.View(inputModel);

        }

        [HttpPost]
        public async Task<IActionResult> EditWithVideo(int id, WebEminarWithVideoViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }


            await this.webEminarService.UpdateWithVideoAsync(id, input);

            return this.RedirectToAction("IndexWebEminarsWithVideos");
        }
        public IActionResult IzminalToKachen(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var items = this.context.WebEminars;
            if (items.Any(webEminar => webEminar.AddedByUserId == userId))
            {
                var inputModel = this.webEminarService.GetById<WebEminarWithVideoViewModel>(id);

                inputModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

                return this.View(inputModel);
            }
            else
            {
                throw new ApplicationException();
            }
        }

        [HttpPost]
        public async Task<IActionResult> IzminalToKachen(int id, WebEminarWithVideoViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }


            await this.webEminarService.IzminalToKachen(id, input);

            return this.RedirectToAction("IndexWebEminarsWithVideos");
        }

        // GET: Administration/WebEminars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return this.NotFound();
            }

            var webEminar = await this.dataRepository
                .AllWithDeleted()
                .FirstOrDefaultAsync(m => m.Id == id);

            if (webEminar == null)
            {
                return this.NotFound();
            }

            return this.View(webEminar);
        }

        // POST: Administration/WebEminars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var webEminar = this.dataRepository
              .AllWithDeleted()
              .FirstOrDefault(x => x.Id == id);
            var userBookings = this.context.UserBookings.Where(x => x.WebEminarId == id).ToList();
            var votes = this.context.Votes.Where(x => x.WebEminarId == id).ToList();
            var comments = this.context.Comments.Where(x => x.WebEminarId == id).ToList();
            var reports = this.context.Reports.Where(x => x.WebEminarId == id).ToList();
            var likes = this.context.Likes.Where(x => x.WebEminarId == id).ToList();
            foreach (var item in reports)
            {
                this.reportsRepository.HardDelete(item);
            }
            foreach (var item in comments)
            {
                this.commentsRepository.HardDelete(item);
            }
            foreach (var item in votes)
            {

Web/WebEminari.Web/Views/Report/CommentEdit.cshtml
@model WebEminari.Web.ViewModels.Reports.Comments.CommentReportEditModel
@{ ViewData["Title"] = "Editing comment report #" + Model.ReportId; }

<div class="container">
    <div class="col-sm-10 offset-sm-1 col-md-6 offset-md-3 text-center">
        <div class="card card-style-40-rem mb-2">
            <div>
                <div class="card-body">
                    <h5 class="card-title">Editing report for the following comment</h5>
                    <hr />
                    <p class="card-text">@Model.CommentApplicationUserUserName</p>
                    <p class="card-text">@Model.CommentContent</p>
                    <p class="card-text">
                        @{ var createdBy = Model.ApplicationUserUserName ?? "Deleted User"; }
                        @*<div>
                <small class="text-muted">Created by - @createdBy</small>
            </div>*@
                        <div>
                            <small class="text-muted">Date created - <time datetime="@Model.CommentCreatedOn.ToString("O")">@Model.CommentCreatedOn.ToString("g")</time></small>
                        </div>
                    </p>
                </div>
            </div>
        </div>
        <div class="text-center">
            <h3 class="text-center">Editing report #@Model.ReportId | Comment #@Model.CommentId</h3>
            <hr />
            <form asp-controller="Report" asp-action="CommentEdit" method="post">
                <input type="hidden" value="@Model.CommentId" asp-for="@Model.CommentId" class="form-control" />
                <input type="hidden" value="@Model.ReportId" asp-for="@Model.ReportId" class="form-control" />
                <input type="hidden" value="@Model.ApplicationUserId" asp-for="@Model.ApplicationUserId" class="form-control" />
                <div class="form-group">
                    <label asp-for="Subject"></label>
                    <input asp-for="Subject" class="form-control" />
                    <span asp-validation-for="Subject" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ReportDescription"></label>
                    <textarea asp-for="ReportDescription" class="form-control"></textarea>
                    <span asp-validation-for="ReportDescription" class="text-danger"></span>
                </div>

                <input class="btn btn-sm btn-outline-success" type="submit" value="Save" />
                <a asp-controller="WebEminars" asp-action="Details" asp-route-id="@Model.WebEminarId" class="btn btn-sm btn-outline-dark">
                    Cancel
                </a>
            </form>
        </div>
    </div>
    <a asp-controller="WebEminars" asp-action="All" class="btn btn-sm btn-outline-dark"><i class="fas fa-arrow-left"></i> Back to all</a>
</div>

Web/WebEminari.Web/Views/Report/CommentReportsCreatedByMe.cshtml
@model IEnumerable<WebEminari.Web.ViewModels.Reports.Comments.CommentReportViewModel>
@{ ViewData["Title"] = "Comments reported by me"; }

<div class="container">
    <div class="row">
        @foreach (var report in Model)
        {
<div class="col-lg-4 pb-3">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="card-title">Comment details</h5>
            <hr />
            <div class="card-text">
                <h5>@report.CommentContent</h5>

                <div>
                    <small class="text-muted">Created by - @report.CommentApplicationUserUserName</small>
                </div>
                <div>
                    <small class="text-muted">Date created - <time datetime="@report.CommentCreatedOn.ToString("O")">@report.CommentCreatedOn.ToString("g")</time></small>
                </div>
            </div>
            <div class="mt-3">
                <a asp-controller="WebEminars" asp-action="Details" asp-route-id="@report.WebEminarId" class="btn btn-sm btn-outline-dark mb-1">
                    <i class="fas fa-info"></i> Details
                </a>
            </div>
        </div>
        <div class="card-body text-center">
            <h5>Report details</h5>
            <hr />
            <div class="form-group">
                <label asp-for="@report.Subject"></label>
                <h6 class="card-title">@report.Subject</h6>
            </div>
            <div class="form-group">
                <label asp-for="@report.ReportDescription"></label>
                <h6 class="card-text">@report.ReportDescription</h6>
            </div>
            <div class="form-group">
                <label asp-for="@report.CreatedOn">Date created</label>
                <h6 class="card-text"><time datetime="@report.CreatedOn.ToString("O")">@report.CreatedOn.ToString("g")</time></h6>
            </div>
            <a asp-controller="Report" asp-action="CommentEdit" asp-route-reportid="@report.ReportId" class="btn btn-sm btn-outline-success mb-2">
                <i class="fas fa-edit"></i> Edit
            </a>
            <a asp-controller="Report" asp-action="CommentDelete" asp-route-reportid="@report.ReportId" class="btn btn-sm btn-outline-danger mb-2">
                <i class="fas fa-trash-alt"></i> Delete
            </a>
        </div>
    </div>
</div>}
    </div>
    @if (!Model.Any())
    {
<h3 class="text-center">You don't have any reports to comments yet.</h3>
                <hr />}
    @if (this.User.IsInRole("Administrator"))
    {
<a class="btn btn-primary" asp-area="Administration" asp-controller="Reports" asp-action="IndexComments">Back to admin</a> }
            else
            {
<a class="btn btn-primary" asp-action="CommentsReports">Back to admin</a>}
</div>

Web/WebEminari.Web/Views/Report/CommentsReports.cshtml
@model IEnumerable<AdminReportViewModel>

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Tables</title>

    <!-- Custom fonts for this template -->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <partial name="_UserAdminNav" />
    <!-- End of Topbar -->
    <!-- Begin Page Content -->
    <div class="container-fluid">


        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Репорти на коментари</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>
                                    Created By
                                </th>
                                <th>
                                    Comment Content
                                </th>
                                <th>
                                    Report Subject
                                </th>
                                <th>
                                    Report Content
                                </th>
                                <th>
                                    CreatedOn
                                </th>
                                <th>
                                    Buttons
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in this.Model)
                            {
                                <tr class="Search">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ApplicationUserUserName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CommentContent)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Subject)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        <time datetime="@item.CreatedOn.ToString("O")">@item.CreatedOn.ToString("g")</time>
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a class="btn btn-dark" asp-controller="Report" asp-action="CommentEdit" asp-route-reportid="@item.Id">Edit</a>
                                            <a class="btn btn-danger" asp-controller="Report" asp-action="CommentDelete" asp-route-reportid="@item.Id">Delete</a>
                                            <a class="btn btn-info" asp-controller="WebEminars" asp-action="Details" asp-route-id="@item.WebEminarId">Details</a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/datatables-demo.js"></script>
    <script src="~/lib/luxon/luxon.min.js"></script>
    <script src="~/js/site.js"></script>
</body>

</html>

Web/WebEminari.Web/Views/Report/WebEminarReportsCreatedByMe.cshtml
@model IEnumerable<WebEminari.Web.ViewModels.Reports.WebEminars.WebEminarReportViewModel>
@{ ViewData["Title"] = "WebEminars reported by me"; }

<div class="container pb-3">
    <div class="row">
        @foreach (var report in Model)
        {
<div class="col-lg-4 pb-3">
    <div style="margin: 20px" class="card">
        <div class="card-body text-center">
            <h5 class="card-title">Уеб Семинар</h5>
            <hr />
            <h5 class="card-text">@report.WebEminarTitle</h5>

            <div class="card-text mb-2">
                <div>
                    <small class="text-muted">Created by - @report.WebEminarAddedByUserUserName</small>
                </div>
                <div>
                    <small class="text-muted">Category - @report.WebEminarCategoryName</small>
                </div>
                <div>
                    <small class="text-muted">Date created - <time datetime="@report.WebEminarCreatedOn.ToString("O")">@report.WebEminarCreatedOn.ToString("g")</time></small>
                </div>
            </div>

            <div class="mt-3">
                <a asp-controller="WebEminars" asp-action="Details" asp-route-id="@report.WebEminarId" class="btn btn-sm btn-outline-dark mb-1">
                    <i class="fas fa-info"></i> Details
                </a>
            </div>
        </div>

        <div class="card-body text-center">
            <h5>Репорт</h5>
            <hr />
            <div class="form-group">
                <label>Причина</label>
                <h6 class="card-title">@report.Subject</h6>
            </div>
            <div class="form-group">
                <label>Описание</label>
                <h6 class="card-text">@report.ReportDescription</h6>
            </div>
            <div class="form-group">
                <label asp-for="@report.CreatedOn">Date created</label>
                <h6 class="card-text"><time datetime="@report.CreatedOn.ToString("O")">@report.CreatedOn.ToString("g")</time></h6>
            </div>

            <a asp-controller="Report" asp-action="WebEminarEdit" asp-route-reportid="@report.ReportId" class="btn btn-sm btn-outline-success mb-2">
                <i class="fas fa-edit"></i> Edit
            </a>
            <a asp-controller="Report" asp-action="WebEminarDelete" asp-route-reportid="@report.ReportId" class="btn btn-sm btn-outline-danger mb-2">
                <i class="fas fa-trash-alt"></i> Delete
            </a>
        </div>
    </div>
</div>}
    </div>

    @*<partial name="_MultipleLessonsPartial" />*@
    @if (!Model.Any())
    {
<h3 class="text-center">You don't have any reports to webinars yet.</h3>
                <hr />}
    @if (this.User.IsInRole("Administrator"))
    {
<a class="btn btn-primary" asp-area="Administration" asp-controller="Reports" asp-action="IndexWebEminars">Back to admin</a>
}
else
{
<a class="btn btn-primary" asp-action="WebEminarsReports">Back to admin</a>
}

</div>

@section Scripts {
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6,Array.prototype.includes,CustomEvent,Object.entries,Object.values,URL"></script>
    <script src="https://unpkg.com/plyr@3"></script>
    <script>const players = Array.from(document.querySelectorAll('.js-player')).map(p => new Plyr(p));
        window.player = player;</script>
}